apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
