apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: evekill
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "pods/log"]
    verbs: ["get", "list", "watch"]
